name: Release

on:
    push:
        tags: "*"

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 20.9.0
              uses: actions/setup-node@v1
              with:
                  node-version: 20.9.0
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm run package
            - run: npx vsce publish
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
